name: CI

on:
  push:
    branches:
      - "main" # Ensure this matches your branch name (e.g., "master" or "main")

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # IMPORTANT: Replace 'your-dockerhub-username/your-repo-name' with your actual Docker Hub details
          tags: shahhalaya/my-ai-app:latest
